### ISSUE TITLE
Calculation of TacGenericConverter production

### ISSUE THREAD

**Issue by rogersk** [JPLRepo/AmpYear#20]
AY picks up the EC production ratio ( ==1, from `outputResources`), but does not quantify it by the module's `conversionRate`.

The stock Fuel Cell and Fuel Cell Array w/TACLS currently indicate +1 EC/s, but they produce 0.75 and 4.5 EC respectively.

**Comment by JPLRepo** [comment]
@rogersk - Thanks. Will fix in the upcoming KSP 1.1 release version.
Update: Not sure I am following what you are talking about with the fuel cell's. Are these stock parts or TACLS parts? Can you supply the name of the parts and where they are from.

**Comment by rogersk** [comment]
actually those are the stocks with TACLS patches from RO :) sorry

> PART[FuelCell]:FOR[RealismOverhaul]
> PART[FuelCellArray]:FOR[RealismOverhaul]

```
MODULE
    {
        name = TacGenericConverter  
        converterName = Fuel Cell
        conversionRate = 0.75
        inputResources = LqdHydrogen, 0.000134718, LqdOxygen, 0.000095599
        outputResources = Water, 0.0001186, true, ElectricCharge, 1, true
    }
```

but all TACLS converters work this way, just none of the default ones produces electricity

```
        // A comma separated list of resources to use as inputs.
        // For each resource, list the resource name and the amount (which
        // is multiplied by the conversionRate)
        inputResources = IntakeAir, 0.1, ElectricCharge, 1

        // A comma separated list of resources to output. Same as above
        // but also specify whether it should keep converting if the
        // resource is full (generating excess that will be thrown away).
        outputResources = Oxygen, 0.063829787234043, false
```

**Comment by JPLRepo** [comment]
Believe this is now fixed in V1.3 - please confirm.
https://github.com/JPLRepo/AmpYear/commit/c669fe224e8bde47c0394238320a9659cdb6835c

**Comment by rogersk** [comment]
thanks, will check it when TACLS and/or RO upgrades to 1.1

**Comment by JPLRepo** [comment]
Both are upgraded now to 1.1.x. Can you check and report back please.

**Comment by JPLRepo** [comment]
Closing as no response.
