### ISSUE TITLE
Additional Modules & Some Suggestions

### ISSUE THREAD

**Issue by deimos790** [JPLRepo/AmpYear#23]
From the forum post:
-      What about ModuleGenerator?
-     Combine solar panels modules into one option (curved/regular)?
-     Combine Data Transmitters into one option? RemoteTech users aren't using regular DataTransmitters and regular DataTransmitter users aren't using RemoteTech
-     A lot of lights use AnimationGeneric (although I don't think that has a resource cost associated with it, so I guess it doesn't really matter then).
-     RWSaturatable module (saturatable reaction wheel mod)
-     Is it smart (i.e. pull from list of installed mods?) or did you have to add these manually? I'm guessing manually. ---_This is more of a question than a suggestion._
-     How are the average users supposed to know which module corresponds to which ingame item? You and I might know, but they might not. Maybe a tooltip or a descriptive text (resourceharvestor = drill).

**Comment by JPLRepo** [comment]
ModuleGenerator is already catered for? Will check Module Generator is already coded. Require further information on what you see, that makes you think it is not.

Require Clarification for these two are you suggesting combining them in the Settings Menu? Or everywhere.   
-  Combine solar panels modules into one option (curved/regular)?  
- Combine Data Transmitters into one option? RemoteTech users aren't using regular DataTransmitters and regular DataTransmitter users aren't using RemoteTech  

Lights: Not going to do anything there. ModuleLight is handled as well as Avaition Lights modules. ModuleAnimateGeneric does not use EC.   

RWSaturatable - Will look at that if they fix their bugs. It's throwing Null Reference errors. I'd advise not using it until fixed.   

No it's not smart (already answered this on the forum).   

I'll look at what's available other than the module name. But I'm not going to build my own list.   Actually I thought of this a while ago, so perhaps this would help. Part highlighting when you hover over a part in the part list.

**Comment by JPLRepo** [comment]
Module Generator is already catered for. More information required if there is a bug.  
Require further information as above for the combining request?  
Changed from using Part Name to the Title Name for a part. But left ModuleNames in.  
Investigating part highlighting.
