### ISSUE TITLE
Realism Overhaul support?

### ISSUE THREAD

**Issue by JPLRepo** [JPLRepo/AmpYear#25]
it doesn't seem to be recognising power draw required for command on probe cores?? for example, the able avionics package uses 150 watts, but ampyear shows command as showing as 0

**Comment by JPLRepo** [comment]
<Agathorn> <NathanKell> 116,000 / ((10w + (3000/60)w) / 1000)
<Agathorn> <Agathorn> so ECx1000/60 = w
<Agathorn> <Agathorn> 1w = 1000EC/sec?
<Agathorn> <NathanKell> 1w for 1s = 1/1000 EC
<Agathorn> <NathanKell> (1 EC = 1000J and 1w = 1J/sec)

AmpYear needs to recognise when RO is installed and convert EC and show appropriately.

**Comment by jwvanderbeck** [comment]
see also: https://github.com/KSP-RO/RealismOverhaul/blob/f7c3f8e5177fa78eb9fbdd0f63da361a562c8541/GameData/RealismOverhaul/RealismOverhaul_Global_Config.cfg#L40-L46

**Comment by JPLRepo** [comment]
Dev version available. Need to do a few other things before full release.  
Added Toggle Button in the top right corner of the Show Parts List window. this toggle will change the display to show Stock EC units or SI units
 (Système international d'unités) showing EC converted to Watts, kiloWatts and megaWatts. (for better Realism Overhaul compatibility).  
 Fixed bug:- ModuleCommand not showing EC usage.  
https://github.com/JPLRepo/AmpYear/releases/tag/V1.3.5-dev

**Comment by JPLRepo** [comment]
Need to do a bit more testing. Noticed some unusual values last night whilst testing fix for reactors.

**Comment by JPLRepo** [comment]
V1.3.5 Deployed
