### ISSUE TITLE
Mod request MKS/OKS

### ISSUE THREAD

**Issue by LeLeon** [JPLRepo/AmpYear#29]
Asking for mod support (nuclear reactors): USI Kolonization Systems (MKS/OKS)

[http://forum.kerbalspaceprogram.com/index.php?/topic/72032-11-usi-kolonization-systems-mksoks-0400-planetary-logistics-and-kolony-rewards/#comment-1139421](MKS mod thread)

Would be fine to see it some day.

**Comment by JPLRepo** [comment]
MKS/OKS nuclear reactors use stock modules. So are already supported.
Your issue as per the forum is that when you install NFE MKS/OKS changes it's reactors to use the NFE FissionReactor and Generator modules. So that's what you really want.
