### ISSUE TITLE
USI-Core Nuclear Reactor floating EC Calculation using Thermal Efficiency

### ISSUE THREAD

**Issue by wile1411** [JPLRepo/AmpYear#36]
AMPYear 1.3.4.0 currently only shows a static 230 EC for a 1.25m Nuclear Reactor from the USI mod family. This value is it's maximum EC output provided it stays within operating temperatures

If you are able to see the Thermal Efficiency value for the reactor, is it possible to change the displayed values for the reactor to the calculated figure (Total EC \* (Thermal Efficiency%)) = Current EC

I tested this using AMPYear 1.3.4.0 and with 2x1.25m USI-Core Reactors (460EC/s) and a healthy 115EC/s load on them. I also had the HotSpot mod installed to see the change in temp of the parts.

[KSP Forum Post Link](http://forum.kerbalspaceprogram.com/index.php?/topic/114991-113-ampyear-main-reserve-power-manager-v1340-27th-june-2016/&do=findComment&comment=2675556)

**Comment by JPLRepo** [comment]
Ok, so somehow I missed this update to ModuleResourceConverter.  
Made changes to include HeatThrottle and Efficiency values.  
This is a generic change as any part using ModuleResourceconverter could use these values.  
USI reactors definitely do!  
To be included in next version.

**Comment by wile1411** [comment]
awesome find and thanks for your work - it's a great mod.

**Comment by JPLRepo** [comment]
V1.3.5 Deployed
