### ISSUE TITLE
RTWrapper is broken with latest RT version

### ISSUE THREAD

**Issue by YamoriYuki** [JPLRepo/AmpYear#54]
In latest version(s) of RemoteTech AmpYear fails to load RTSettings instance. This is caused by serious code cleanup, where the private field `mInstance` read by RTWrapper was renamed. There is a public property `Instance` that should be used.
Also, `ModuleRTAntenna` will be implementing `IResourceConsumer` in the next bugfix version of RT, like any stock module consuming resources, so you should be able to handle RT antennas the same way you handle lights, once it's released.

**Comment by JPLRepo** [comment]
Thanks. I'll take a look one of these years.
Pretty sure I was using mInstance because there wasn't a public one at some stage.. but I could be completely wrong on that one.
