### ISSUE TITLE
USI LS broken with V0.5.10+

### ISSUE THREAD

**Issue by JPLRepo** [JPLRepo/AmpYear#55]
I'm getting log spam

[LOG 13:23:09.579] 12/2/2016 1:23:09 PM,AmpYear-USILSWrapper,Invoke LifeSupportRecipe Method failed: Object reference not set to an instance of an object
[LOG 13:23:09.579] 12/2/2016 1:23:09 PM,AmpYear,Wrong USI LS version - disabled.

in flight with USI LS v0.5.12, and as far back as at least v0.5.10 (probably even earlier). Apparently there have been some breaking API changes?

**Comment by MaxRebo1** [comment]
I suggest removing USI-LS support for now. The log spam is worse than AmpYear not calculating EC consumption correctly.

Just doing
```USILSPresent = false;```
in [AYController.cs#L247](https://github.com/JPLRepo/AmpYear/blob/master/AYController.cs#L247) should do the trick I think?

**Comment by JPLRepo** [comment]
That's the plan. I plan to remove support for USI LS as I don't use it myself.

**Comment by JPLRepo** [comment]
I've removed the ModuleLifeSupport - Support.
And left the Resource converters that are part of USI-LS in. as they are working.

**Comment by Blu3wolf** [comment]
Might it be better to update the forum thread OP to indicate USI-LS is no longer supported? Took me a little while to figure out why my vessels were running out of power 'early'.

**Comment by JPLRepo** [comment]
Oh I see. you mean the Opening Post under supported mods?
As it is in the changelog.
Actually it says Partial already... I have highlighted the Partial

**Comment by Blu3wolf** [comment]
I guess I misunderstood partial support then. It seems like the mod doesnt recognise USI-Ls at all, but it did in the past. Obviously it is your choice what to support, and if its a great deal of work to support then obviously you will choose to use your time wisely and as you see fit. It was just the OP that seemed to indicate support did exist for the mod and my limited testing in my new career save that seemed to contradict that.

**Comment by JPLRepo** [comment]
It is more the fact that the author of USI has changed things and continues to change things as I noticed a lot of bugs being reported for that mod. So as I am extremely time poor I will pick it up again when it stops changing so much. Given that I don't use USI mods myself, it's low down my list as well.
