### ISSUE TITLE
RTG EC production not tracked

### ISSUE THREAD

**Issue by rogersk** [JPLRepo/AmpYear#61]
in the VAB, AY detects and accounts for the part's output (750W for the stock RTG)
when launched, it does not anymore:

![ampyear-rtg](https://cloud.githubusercontent.com/assets/1174125/21793971/63b5458c-d6f6-11e6-89ac-a36ea74c960b.png)
v1.4.4.0 @ KSP v1.2.2

**Comment by JPLRepo** [comment]
Indeed after some deeper investigation I have discovered that stock code is not doing what I thought it was for output EC. so I'm working on a work-around.

**Comment by JPLRepo** [comment]
Fixed ModuleGenerator and ModuleAlternator outputs.

**Comment by JPLRepo** [comment]
V1.4.5.0 fixed this.

**Comment by rogersk** [comment]
now the calculation is broken in VAB (shows 0) :(

**Comment by JPLRepo** [comment]
D'oh.
