### ISSUE TITLE
UI "Capacity" vs megawatts, units & wording

### ISSUE THREAD

**Issue by rogersk** [JPLRepo/AmpYear#66]
first, indication of **megawatt** uses wrong prefix (4000EC is shown as 4mW, not 4MW) - in capacity and in flow values. 

during construction, indicating capacity in same units as flow (EC or W) is misleading.
especially in "SI" mode, watt capacity should be displayed as a function of time. like 
1) **kW.s-1** (1kWs = 1EC/s). 
2) preferred, more common W.h-1 would require additional conversion (1kWh = 3600 EC/s) and could be yet another source of confusion :) 
3) just leave the unit blank for capacity, although the 1000 steps would be in the way then  

in flight, this is a non-problem, by indicating it in % which is explicit and dimensionless.

**Comment by JPLRepo** [comment]
I think people may be confused using kWh.
How about:
W.s
kW.s
MW.s

**Comment by JPLRepo** [comment]
No response so I am going with above.
