### ISSUE TITLE
Issues with ReservePower in Realism Overhaul [MOD 1.4.6.0][KSP 1.2.2]

### ISSUE THREAD

**Issue by Patrykz94** [JPLRepo/AmpYear#73]
I tried it with two different installs (manual & CKAN) and each time when I install AmpYear, almost all command pods and probe cores get removed from the game.
Looks like it's an issue with the ReservePower resource being added to those parts.
Removing these few lines of code from the config file fixed it for me:
https://github.com/JPLRepo/AmpYear/blob/V1.4.6.0/Distribution/GameData/REPOSoftTech/AmpYear/MMConfigAmpYear.cfg#L17-L22

**Comment by JPLRepo** [comment]
Yes. You are using an old version.
It is fixed in the latest release.
https://github.com/JPLRepo/AmpYear/blob/master/Distribution/GameData/REPOSoftTech/AmpYear/MMConfigAmpYear.cfg

**Comment by JPLRepo** [comment]
... and no, I don't do backward version changes or support old versions.
But you can just take that one from the master and use that.
