### ISSUE TITLE
Dark side surface calc

### ISSUE THREAD

**Issue by Skippyy** [JPLRepo/AmpYear#75]
The Surface Darkness Time for all moons in the game is showing as t - 0-3:0-14:0-8 which is causing a bunch of infinities and NaNs to crop up. I noticed the same number shows up as the mains and reserve time when the power drain is 0. Happens on both  modded and clean installs.

logs https://drive.google.com/open?id=0B9i3fdwNfFPrYm8wS3duWVhQT3M

**Comment by JPLRepo** [comment]
The readout is a stock bug in time display.
the calcs were incorrect. Fixed for next version.
