### ISSUE TITLE
Solar panels retracted at 1% power.

### ISSUE THREAD

**Issue by Bear67** [JPLRepo/AmpYear#83]
Can't Extend panels while there being retracted.
![screenshot14](https://user-images.githubusercontent.com/5138687/31867207-c1ba502e-b750-11e7-9071-dc47b2249bf8.png)
Also the Reserved power doesn't seen to be getting use (Non-Isolated).

KSP 1.3 - AmpYear 1.5

**Comment by JPLRepo** [comment]
Not sure I understand the first bit about the solar panels...
as for reserve power. It's not automatically used. You have to transfer it manually.
